Record on CI

diff --git a/.github/workflows/comparison-tests.yml b/.github/workflows/comparison-tests.yml
--- a/.github/workflows/comparison-tests.yml
+++ b/.github/workflows/comparison-tests.yml
@@ -29,5 +29,6 @@ jobs:
       - name: Run comparison tests in record mode
         run: pnpm test:comparison:record
 
-      - name: Run comparison tests after record mode
-        run: pnpm test:comparison
+      # Fail if there are any diffs
+      - name: Fail if there are any diffs
+        run: if [ -n "$(git diff --name-only)" ]; then exit 1; fi
